#ifndef ERRORCODES_H
#define ERRORCODES_H

#define EXIT_SUCCESS 0
#define EXIT_INVALID_ARGS_COUNT 1
#define EXIT_INVALID_ARGS 2
#define EXIT_FILE_CANT_BE_OPENED 3
#define EXIT_NO_MEMORY 4
#define EXIT_INVALID_FILE_CONTENT 5
#define EXIT_FILE_NO_ACCESS 6
#define EXIT_EMPTY_RESULT_ARRAY 7
#define EXIT_NULLPTR_INPUT 8
#define EXIT_EMPTY_FILE 9

#endif
